services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
  reservations:
    image: me-west1-docker.pkg.dev/bookify-401118/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: me-west1-docker.pkg.dev/bookify-401118/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: me-west1-docker.pkg.dev/bookify-401118/payments/production
    env_file:
      - ../apps/payments/.env
  notifications:
    image: me-west1-docker.pkg.dev/bookify-401118/notifications/production
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo
